/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

type ErrorWithCode = Error & { code: number }
type MaybeErrorWithCode = ErrorWithCode | null | undefined

const createErrorFromCodeLookup: Map<number, () => ErrorWithCode> = new Map()
const createErrorFromNameLookup: Map<string, () => ErrorWithCode> = new Map()

/**
 * BadAccountData: 'Existing account data cannot be parsed'
 *
 * @category Errors
 * @category generated
 */
export class BadAccountDataError extends Error {
  readonly code: number = 0x1770
  readonly name: string = 'BadAccountData'
  constructor() {
    super('Existing account data cannot be parsed')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, BadAccountDataError)
    }
  }
}

createErrorFromCodeLookup.set(0x1770, () => new BadAccountDataError())
createErrorFromNameLookup.set('BadAccountData', () => new BadAccountDataError())

/**
 * InvalidAccountData: 'The pyth account could not be parsed'
 *
 * @category Errors
 * @category generated
 */
export class InvalidAccountDataError extends Error {
  readonly code: number = 0x1771
  readonly name: string = 'InvalidAccountData'
  constructor() {
    super('The pyth account could not be parsed')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, InvalidAccountDataError)
    }
  }
}

createErrorFromCodeLookup.set(0x1771, () => new InvalidAccountDataError())
createErrorFromNameLookup.set(
  'InvalidAccountData',
  () => new InvalidAccountDataError()
)

/**
 * Attempts to resolve a custom program error from the provided error code.
 * @category Errors
 * @category generated
 */
export function errorFromCode(code: number): MaybeErrorWithCode {
  const createError = createErrorFromCodeLookup.get(code)
  return createError != null ? createError() : null
}

/**
 * Attempts to resolve a custom program error from the provided error name, i.e. 'Unauthorized'.
 * @category Errors
 * @category generated
 */
export function errorFromName(name: string): MaybeErrorWithCode {
  const createError = createErrorFromNameLookup.get(name)
  return createError != null ? createError() : null
}
